<a href="https://colab.research.google.com/github/pooriaazami/deep_learning_class_notebooks/blob/main/Pytorch_Introdution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
scaler = torch.tensor([1.])

In [5]:
scaler

tensor([1.])

In [6]:
scaler.ndim

1

In [7]:
scaler.dtype

torch.float32

In [8]:
scaler + 2

tensor([3.])

In [9]:
scaler.requires_grad

False

In [10]:
scaler.device

device(type='cpu')

In [15]:
torch.cuda.is_available()

False

In [12]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [13]:
device

'cpu'

In [14]:
scaler = scaler.to(device)

In [22]:
class Network(nn.Module):
  def __init__(self):
    super().__init__()

    self.fc1 = nn.Linear(in_features=2, out_features=10)
    self.fc2 = nn.Linear(in_features=10, out_features=10)
    self.fc3 = nn.Linear(in_features=10, out_features=10)
    self.fc4 = nn.Linear(in_features=10, out_features=1)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = F.relu(self.fc3(x))
    x = self.fc4(x)

    return x

In [23]:
net = Network().to(device)

In [24]:
test_input = torch.rand((3, 2))
test_input

tensor([[0.7418, 0.8436],
        [0.8179, 0.3327],
        [0.5869, 0.7119]])

In [25]:
test_output = net(test_input)
test_output

tensor([[0.2814],
        [0.2967],
        [0.2830]], grad_fn=<AddmmBackward0>)

In [26]:
net

Network(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=10, bias=True)
  (fc4): Linear(in_features=10, out_features=1, bias=True)
)

In [30]:
list(net.fc1.parameters())

[Parameter containing:
 tensor([[-0.0678,  0.4129],
         [-0.2128,  0.5182],
         [ 0.3328, -0.5278],
         [-0.0189,  0.6389],
         [ 0.3837,  0.2405],
         [-0.2676, -0.2395],
         [ 0.2778,  0.0328],
         [-0.4963,  0.5281],
         [ 0.1273, -0.0240],
         [-0.4277, -0.5793]], requires_grad=True),
 Parameter containing:
 tensor([-0.5801,  0.0506,  0.2750, -0.6558, -0.2582, -0.3598, -0.5241, -0.0149,
         -0.2104, -0.5190], requires_grad=True)]